%YAML:1.0


TrackerBaseOptions.Level: 4
TrackerBaseOptions.TemplateSize: 8
TrackerBaseOptions.Scale: 0.5

LKTracker.Inverse: 1
# 并行的设置在 LK_slef_tracker.h 中进行设置

DirectTracker.Camera.fx: 718.856
DirectTracker.Camera.fy: 718.856
DirectTracker.Camera.cx: 607.1928
DirectTracker.Camera.cy: 185.2157
DirectTracker.Camera.baseline: 0.573

DirectTracker.nPoints: 2000
DirectTracker.boarder: 20 